name: Loaner daily update

on:
  schedule:
    - cron: '0 0 * * *'   # JST 9:00
  workflow_dispatch:      # 手動実行

permissions:
  contents: write

env:
  CONTACT_PATH: contact.html   # contact.html の場所。別パスならここを変える

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run updater
        env:
          LOANER_URL: ${{ secrets.LOANER_URL }}
          CONTACT_PATH: ${{ env.CONTACT_PATH }}
        run: |
          set -euo pipefail
          javac .github/scripts/LoanerUpdater.java
          java -cp .github/scripts LoanerUpdater

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore: daily loaner update"
            git push
          else
            echo "No changes to commit."
          fi
